version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: gigarick-bot-psql-db
        environment:
            POSTGRES_USER: harsh
            POSTGRES_PASSWORD: patel
            POSTGRES_DB: discordbot
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
